name: Build Multi-Arch Caddy Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - refs.txt
  pull_request:
    branches:
      - main
    paths:
      - refs.txt

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Parse refs.txt for component versions
        id: refs
        run: |
          while IFS== read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
          done < refs.txt

      - name: Build and push multi-arch image with Buildah
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ghcr.io/${{ github.repository }}/caddy
          tags: latest
          containerfiles: ./Caddy/Dockerfile.caddy
          platforms: linux/amd64,linux/arm64
          oci: true
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            CADDY_IMAGE_VERSION=${{ env.caddy-image }}
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            GITHUB_SHA=${{ github.sha }}
            CADDY_CROWDSEC_BOUNCER_VERSION=${{ env.caddy-crowdsec-bouncer }}
            CADDY_DNS_INWX_VERSION=${{ env.caddy-dns-inwx }}
